jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio flake8 isort black mypy

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Lint: flake8
        run: flake8 app tests

      - name: Lint: isort
        run: isort app tests --check-only --diff

      - name: Lint: black
        run: black app tests --check --diff

      - name: Type-check: mypy
        run: mypy app

      - name: Run tests
        run: pytest